### ISSUE TITLE
Ghidra won't disassemble

### ISSUE THREAD

**Issue by AndnixSH** [kp7742/MemDumper#1]
Ghidra won't disassemble dumped lib at all. Just like this and done. 
IDA disassemble fine but some functions can't create pseduocode
Can it be fixed? or Ghidra should fix it?

![image](https://user-images.githubusercontent.com/40742924/79608889-07d60c80-80f6-11ea-989c-462ff490adfc.png)

**Comment by kp7742** [comment]
did you dump raw lib or let it rebuilding?

**Comment by AndnixSH** [comment]
I let it rebuild so I can XREF the strings

**Comment by kp7742** [comment]
try raw dump, it might work

**Comment by AndnixSH** [comment]
That worked, thanks!
